# Generated by Django 4.1.6 on 2023-02-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfectmatch', '0002_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paymentid',
            field=models.TextField(default='ss'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscriptiontype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
