# Generated by Django 4.1.6 on 2023-02-04 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfectmatch', '0003_userprofile_paymentid_userprofile_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
