# Generated by Django 4.1.6 on 2023-02-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfectmatch', '0004_remove_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='paymentid',
            field=models.TextField(null=True),
        ),
    ]
