# Generated by Django 4.1.6 on 2023-02-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfectmatch', '0005_alter_userprofile_paymentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blocklist',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reportlist',
            field=models.TextField(null=True),
        ),
    ]
