# Generated by Django 4.1.6 on 2023-02-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfectmatch', '0006_alter_userprofile_blocklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blocklist',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reportlist',
            field=models.TextField(default='[]', null=True),
        ),
    ]
