# Generated by Django 4.1.6 on 2023-02-06 20:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfectmatch', '0007_alter_userprofile_blocklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo1',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='photo1'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo2',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='photo2'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo3',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='photo3'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo4',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='photo4'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo5',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='photo5'),
        ),
    ]
