# Generated by Django 4.1.6 on 2023-02-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfectmatch', '0011_userprofile_deviceid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('update', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'versioning',
            },
        ),
    ]
